name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip git zip unzip openjdk-17-jdk

    - name: Install Buildozer
      run: |
        pip3 install --user buildozer cython
        export PATH="$HOME/.local/bin:$PATH"

    - name: Build APK with license acceptance
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        # Πρώτο build για κατέβασμα SDK (θα αποτύχει)
        buildozer android debug || true
        # Αποδοχή αδειών
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        # Δεύτερο build (θα λειτουργήσει)
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: HistoriaGrade3-APK
        path: bin/*.apk
