name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build APK
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        workdir: .
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: HistoriaGrade3-APK
        path: bin/*.apk
