name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Android SDK with accepted licenses
      uses: android-actions/setup-android@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Buildozer and dependencies
      run: |
        pip install buildozer cython
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev

    - name: Build APK
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: HistoriaGrade3-APK
        path: bin/*.apk
